"""Validated domain models shared across the analytics pipeline."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from ipaddress import IPv4Address, IPv6Address
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

IPAddress = IPv4Address | IPv6Address


class LogSource(StrEnum):
    """Supported infrastructure log sources."""

    CISCO_IOS = "cisco_ios"
    LINUX_AUTH = "linux_auth"
    AWS_CLOUDTRAIL = "aws_cloudtrail"


class EventOutcome(StrEnum):
    """Normalized event outcomes."""

    SUCCESS = "success"
    FAILURE = "failure"
    UNKNOWN = "unknown"


class Severity(StrEnum):
    """Alert severity levels."""

    INFORMATIONAL = "informational"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SecurityEvent(BaseModel):
    """Normalized event generated by any supported log parser."""

    model_config = ConfigDict(extra="forbid")

    event_id: UUID = Field(default_factory=uuid4)
    timestamp: datetime
    source: LogSource
    category: list[str] = Field(default_factory=list)
    event_type: list[str] = Field(default_factory=list)
    outcome: EventOutcome = EventOutcome.UNKNOWN
    action: str
    message: str
    host_name: str | None = None
    source_ip: IPAddress | None = None
    user_name: str | None = None
    resource: str | None = None
    raw_event: str | dict[str, Any]
    attributes: dict[str, Any] = Field(default_factory=dict)

    @field_validator("timestamp")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        """Convert every event timestamp to timezone-aware UTC."""

        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)

        return value.astimezone(UTC)


class ParseFailure(BaseModel):
    """A log entry rejected by a parser with its failure reason."""

    model_config = ConfigDict(extra="forbid")

    line_number: int = Field(ge=1)
    reason: str
    raw_event: str


class ParseBatch(BaseModel):
    """Events and rejected records returned from one parser execution."""

    model_config = ConfigDict(extra="forbid")

    events: list[SecurityEvent] = Field(default_factory=list)
    rejected: list[ParseFailure] = Field(default_factory=list)


class DetectionAlert(BaseModel):
    """Correlated security alert produced by the detection engine."""

    model_config = ConfigDict(extra="forbid")

    alert_id: UUID = Field(default_factory=uuid4)
    rule_id: str
    title: str
    description: str
    detected_at: datetime
    severity: Severity
    risk_score: int = Field(ge=0, le=100)
    source: LogSource
    source_ip: IPAddress | None = None
    user_name: str | None = None
    resource: str | None = None
    mitre_techniques: list[str] = Field(default_factory=list)
    event_ids: list[UUID] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    recommended_action: str
    false_positive_notes: list[str] = Field(default_factory=list)

    @field_validator("detected_at")
    @classmethod
    def normalize_detected_at(cls, value: datetime) -> datetime:
        """Convert alert timestamps to timezone-aware UTC."""

        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)

        return value.astimezone(UTC)